window.PROBLEM_AGES={
"FGG quantum-optimization conjecture":"Open more than 10 years (c. 2014–15)",
"Rectangles, triangles and Schrödinger waves":"New 2026 construction problem",
"Danus fact-graph mathematics agent":"New 2026 research system",
"Autonomous sum-product disproof generation":"2026 replication experiment; target result was already known",
"Cycle Double Cover theorem":"53 years (since Szekeres, 1973)",
"Long intervals without distinct multiples":"New 2026 strengthening of a recent 2026 theorem",
"Benjamini–Hochberg failure under correlated tests":"About 20 years",
"Sabidussi compatibility conjecture":"At least 39 years (in print by 1987)",
"Derivative-free convex optimization lower bound":"30-year gap (since 1996)",
"Hypergraph Moore bound":"18 years (Feige, 2008)",
"Online Beck–Fiala discrepancy":"45-year parent conjecture (Beck–Fiala, 1981); online form is newer",
"Weak Simplex conjecture":"67-year lineage (Shannon, 1959)",
"Krylov complexity saturation":"Recent 2020s research question",
"Tunable multiqubit elegant joint measurements":"New 2026 construction",
"Ripple large-scale formalization":"New 2026 formalization system",
"Banach-space discovery suite":"Mixed ages: five separate research questions",
"Higher-dimensional Jacobian conjecture":"87 years (Keller, 1939)",
"Full replica-symmetry breaking in the SK spin glass":"47-year lineage (Parisi theory, 1979); exact statement is newer",
"Gaussian Moments conjecture":"11 years (proposed in 2015)",
"Stochastic multi-gradient descent rate":"Recent optimization-rate question",
"Improved Korenblum constant bound":"Sharp constant unresolved for at least 27 years (since 1999)",
"Dittert’s conjecture in dimension 16":"At least 39 years (in print by 1987)",
"xz and Mathieu conjectures for SU(2)":"Mathieu conjecture: 29 years (1997); xz formulation is newer",
"Chernoff density strong log-concavity":"12 years (conjectured in 2014)",
"Mod-4 Kawauchi conjecture":"20 years in this mod-4 form (2006); original conjecture dates to 1979",
"Complex Lie algebra without a real form":"New explicit 2026 construction; older structural question",
"Norine antipodal-coloring conjecture":"18 years (posted in 2008)",
"Counting spanning quasi-trees":"Modern complexity-classification gap; no single canonical start year",
"Černý conjecture for one-cluster automata":"62-year parent conjecture (Černý, 1964); subclass program is newer",
"Dense Kt-minor-free graph bound":"Modern quantitative problem; no single conjecture date",
"Maximal topological complexity of symplectic 4-manifolds":"Recent 21st-century program; specific result is new",
"Chromatic symmetric-function counterexamples":"Roughly 31-year Stanley lineage (1995); second conjecture is newer",
"Unconditional unclonable encryption":"Young 2020s open problem",
"Weighted double Eisenstein-series identity":"Conjectured in the author’s thesis; exact start year not stated",
"Cofinite zeros of high derivatives":"53 years since the contradicted 1973 theorem"
};
